services:

  socialdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - "5567:5432"

  quarkus-app:
    build: .
    image: unitiva/my-social-image:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
     QUARKUS_HTTP_CORS_ORIGINS: http://localhost
     DATABASE_HOST: postgres
     DATABASE_PORT: 5432
     DATABASE_NAME: socialdb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: dev
 

# Main Kafka broker 
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Listen on all interfaces, port 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka  # Replace with the container's hostname (optional)

  # Zookeeper service (modify ports if needed)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9050:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
volumes:
  zookeeper-data: {}